#!/usr/bin/env bash
# Install or update the FDE Claude Code setup.
#
#   ~/.claude-shared/               shared context, standards, bin, config
#   ~/.claude-shared/fde-toolkit/   plugin marketplace
#   ~/.claude-profiles/<name>/      one config dir per identity (auth + settings)
#
# Canonical source: this directory. Keep it in ONE private git repository and
# clone it wherever you need it; this script never creates repositories for you.
#
# Usage:
#   ./install.sh                     first install; profiles work msc alt bedrock
#   ./install.sh work bedrock        first install, named profiles only
#   ./install.sh --update            refresh an existing install in place
#   ./install.sh --update --dry-run  show exactly what would change, touch nothing
#   ./install.sh --update --yes      don't ask about each changed file
#
# What this script will never do:
#   - delete anything: files it did not place are left where they are
#   - overwrite a file you changed without showing you the diff first
#   - touch client contexts, intake, run history, credentials or profile settings
#   - initialise a git repository behind your back
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED="${CLAUDE_SHARED:-$HOME/.claude-shared}"
STAMP="$(date +%Y%m%dT%H%M%S)"
BACKUPS="$SHARED/.backups/$STAMP"

MODE=install
DRY=0
ASSUME_YES=0
GIT_INIT=0
PROFILES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --update)   MODE=update; shift ;;
    --dry-run)  DRY=1; shift ;;
    --yes|-y)   ASSUME_YES=1; shift ;;
    --git-init) GIT_INIT=1; shift ;;
    -h|--help)  sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*)         echo "unknown option: $1" >&2; exit 2 ;;
    *)          PROFILES+=("$1"); shift ;;
  esac
done
[[ ${#PROFILES[@]} -eq 0 ]] && PROFILES=(work msc alt bedrock)

say()  { printf '\033[1m==>\033[0m %s\n' "$*"; }
note() { printf '    %s\n' "$*"; }
act()  { if (( DRY )); then printf '    would %s\n' "$*"; else printf '    %s\n' "$*"; fi; }

# The Claude CLI is needed to create profiles and install the plugin — both of
# which only happen on a fresh install. An update just syncs files, so a missing
# claude must not stand between you and an up-to-date controller.
find_claude() {
  command -v claude >/dev/null 2>&1 && return 0
  local candidate
  # Only the per-user install locations. A claude in /usr/local/bin that is not
  # on your PATH is a PATH you chose; this script does not overrule it.
  for candidate in "$HOME/.claude/local/claude" "$HOME/.local/bin/claude"; do
    if [[ -x "$candidate" ]]; then
      PATH="$(dirname "$candidate"):$PATH"; export PATH
      note "found claude at $candidate — it is not on your PATH, so this run uses it directly"
      return 0
    fi
  done
  return 1
}

if ! find_claude; then
  if [[ "$MODE" == "update" ]]; then
    note "claude CLI not found on PATH. That is fine for an update: profiles,"
    note "credentials and plugin installation are untouched in this mode."
  else
    echo "claude CLI not found on PATH. Install Claude Code first — or, if you only" >&2
    echo "want to refresh the toolkit files, run: ./install.sh --update" >&2
    exit 1
  fi
fi

# ---------------------------------------------------------------------------
# Ownership rules. Anything matching PRESERVE belongs to you and is never
# written by this script. Anything matching CONFIRM is shipped by the toolkit
# but routinely customised, so a difference is shown as a diff and only applied
# with your say-so. Everything else is toolkit-owned: it is backed up, then
# replaced.
# ---------------------------------------------------------------------------
PRESERVE=(
  "env.sh"                      # your tokens
  ".env.sh"
  "intake/*"                    # captured Microsoft material
  "runs/*"                      # run history: manifests, approvals, artifacts
  ".backups/*"
  "shared/clients/*"            # client engagement context
)
CONFIRM=(
  "config/agents.json"          # you may add or relabel identities
  "config/routing-policy.json"  # cost weights, tiers and entitlement ceilings are yours
  "config/provider-templates.json"  # which variable isolates which provider's accounts
  "mcp/mcp-servers.json"        # you edit this by design
  "shared/engineering-standards.md"
  "shared/standards-index.md"       # you may amend it alongside the standards
  "prompts/sidecar-preamble.md"     # the standing brief is written in your voice
  "shared/clients/_template.md"
  "CLAUDE.md"
  "fde-toolkit/plugins/fde-core/.mcp.json"   # generated by mcp-sync
  # You may have pinned a different upstream commit with `design-sources update`.
  # Replacing that silently would move a supply-chain pin behind your back.
  "fde-toolkit/plugins/fde-core/vendor/design-sources.lock.json"
)

matches() {  # matches <relpath> <array-name>
  local rel="$1"; shift
  local pat
  for pat in "$@"; do
    # shellcheck disable=SC2053
    [[ "$rel" == $pat ]] && return 0
  done
  return 1
}

changed=0; skipped=0; preserved=0; added=0

sync_file() {  # sync_file <src-abs> <rel-path-under-SHARED>
  # Three statements, not one: bash expands every word of a `local` line before
  # assigning any of them, so `local a="$1" b="$a"` reads a stale or unset $a.
  local s="$1"
  local rel="$2"
  local d="$SHARED/$rel"

  if matches "$rel" "${PRESERVE[@]}"; then
    [[ -e "$d" ]] && { preserved=$((preserved+1)); return 0; }
  fi

  if [[ ! -e "$d" ]]; then
    act "add      $rel"
    (( DRY )) || { mkdir -p "$(dirname "$d")"; cp -p "$s" "$d"; }
    added=$((added+1)); return 0
  fi

  if cmp -s "$s" "$d"; then
    skipped=$((skipped+1)); return 0
  fi

  if matches "$rel" "${CONFIRM[@]}"; then
    printf '\n'
    say "$rel differs from the shipped version"
    diff -u --label "installed: $rel" --label "shipped:   $rel" "$d" "$s" || true
    if (( DRY )); then
      note "would ask whether to replace it (backup first)"
      return 0
    fi
    if (( ! ASSUME_YES )); then
      local reply=""
      if [[ -t 0 ]]; then
        read -r -p "    replace it? your version is backed up either way [y/N] " reply || reply=""
      fi
      if [[ ! "$reply" =~ ^[Yy]$ ]]; then
        if [[ ! -t 0 ]]; then
          note "kept your version (not a terminal, so nothing was asked — pass --yes to replace)"
        else
          note "kept your version"
        fi
        preserved=$((preserved+1)); return 0
      fi
    fi
  fi

  act "update   $rel  (backup: ${BACKUPS#"$HOME"/}/$rel)"
  if (( ! DRY )); then
    mkdir -p "$(dirname "$BACKUPS/$rel")"
    cp -p "$d" "$BACKUPS/$rel"
    cp -p "$s" "$d"
  fi
  changed=$((changed+1))
}

sync_tree() {  # sync_tree <src-dir> <rel-prefix>
  local root="$1" prefix="${2:-}"
  local f rel
  while IFS= read -r -d '' f; do
    rel="${f#"$root"/}"
    [[ -n "$prefix" ]] && rel="$prefix/$rel"
    case "$rel" in
      # .env.sh is a real secrets file that lives beside the source by accident.
      # It is never installed, never updated and never read by this script.
      .env.sh|*/.env.sh|env.sh|*/env.sh) continue ;;
      *.DS_Store|*/.git/*|*/__pycache__/*|*.pyc) continue ;;
    esac
    sync_file "$f" "$rel"
  done < <(find "$root" -type f -print0)
}

# ---- 1. shared assets -------------------------------------------------------
say "syncing shared context into $SHARED"
(( DRY )) || mkdir -p "$SHARED"
sync_tree "$SRC/claude-shared" ""
sync_file "$SRC/shell/claude-profiles.sh" "shell/claude-profiles.sh"
sync_file "$SRC/shell/claude-profile-new" "bin/claude-profile-new"
(( DRY )) || chmod +x "$SHARED/bin/"* 2>/dev/null || true

# ---- 2. toolkit marketplace -------------------------------------------------
# Nothing is removed here. A skill or agent you wrote that this source does not
# ship stays exactly where it is — the previous version deleted the whole tree
# first, which is how hand-written skills disappeared on an upgrade.
say "syncing plugin marketplace into $SHARED/fde-toolkit"
sync_tree "$SRC/fde-toolkit" "fde-toolkit"
(( DRY )) || chmod +x "$SHARED/fde-toolkit/plugins/fde-core/bin/"*.sh 2>/dev/null || true
# The vendored design sources are data. Only the audit/update tool beside them
# is executable, and nothing inside those source trees ever is.
(( DRY )) || chmod +x "$SHARED/fde-toolkit/plugins/fde-core/vendor/bin/design-sources" 2>/dev/null || true
if [[ -x "$SHARED/fde-toolkit/plugins/fde-core/vendor/bin/design-sources" ]] && (( ! DRY )); then
  if "$SHARED/fde-toolkit/plugins/fde-core/vendor/bin/design-sources" audit >/dev/null 2>&1; then
    note "vendored design sources match their lock"
  else
    note "vendored design sources DO NOT match their lock — run:"
    note "  ~/.claude-shared/fde-toolkit/plugins/fde-core/vendor/bin/design-sources audit"
  fi
fi

# ---- 3. directories that must exist but stay yours ---------------------------
for d in intake runs shared/clients config; do
  if [[ ! -d "$SHARED/$d" ]]; then
    act "create   $d/"
    (( DRY )) || mkdir -p "$SHARED/$d"
  fi
done
(( DRY )) || : > "$SHARED/runs/.gitkeep"

if [[ ! -f "$SHARED/env.sh" ]]; then
  act "create   env.sh from the example (fill in your tokens)"
  (( DRY )) || { cp "$SRC/claude-shared/env.sh.example" "$SHARED/env.sh"; chmod 600 "$SHARED/env.sh"; }
fi

if (( ! DRY )); then
  cat > "$SHARED/.gitignore" <<'GI'
env.sh
.env.sh
intake/
runs/*
!runs/.gitkeep
.backups/
__pycache__/
*.pyc
GI
fi

# ---- 4. profiles -------------------------------------------------------------
export CLAUDE_SHARED="$SHARED"
if [[ "$MODE" == "install" ]]; then
  for p in "${PROFILES[@]}"; do
    if [[ -d "$HOME/.claude-profiles/$p" ]]; then
      note "profile $p already exists — its settings.json and credentials are untouched"
      continue
    fi
    say "creating profile: $p"
    (( DRY )) || "$SHARED/bin/claude-profile-new" "$p"
  done

  for p in "${PROFILES[@]}"; do
    dir="$HOME/.claude-profiles/$p"
    say "installing fde-core into profile: $p"
    if (( ! DRY )); then
      CLAUDE_CONFIG_DIR="$dir" claude plugin marketplace add "$SHARED/fde-toolkit" 2>/dev/null || true
      CLAUDE_CONFIG_DIR="$dir" claude plugin install fde-core@fde-toolkit 2>/dev/null || \
        note "(plugin install needs an interactive session first — run 'cc-$p' and use /plugin)"
    fi
  done
else
  note "update mode: profiles, credentials and settings.json left exactly as they are"
fi

# ---- 5. MCP wiring -----------------------------------------------------------
say "syncing MCP config to the agent CLIs that are installed"
if (( DRY )); then
  "$SHARED/bin/mcp-sync" --dry-run 2>/dev/null || note "(mcp-sync dry run unavailable until installed)"
else
  "$SHARED/bin/mcp-sync" || note "(mcp-sync failed — run it by hand later)"
fi

# Only the CLIs this ecosystem actually uses. GitHub Copilot is not one of them,
# so there is nothing to check for and ~/.copilot is never read or written.
for tool in agy codex; do
  if command -v "$tool" >/dev/null 2>&1; then note "found $tool CLI"; else note "$tool CLI not installed — skipped"; fi
done

# .docx intake needs a converter, or ms-intake fails on the one input format
# Copilot Notebooks actually export.
if command -v pandoc >/dev/null 2>&1; then
  note "found pandoc — .docx intake will work"
elif python3 -c "import docx" >/dev/null 2>&1; then
  note "found python-docx — .docx intake will work"
else
  note ".docx intake has no converter. Install one, or ms-intake will only take text:"
  note "    brew install pandoc      # or: pip install python-docx --break-system-packages"
fi

# ---- 6. shell wiring ---------------------------------------------------------
line="source \"\$HOME/.claude-shared/shell/claude-profiles.sh\"
export PATH=\"\$HOME/.claude-shared/bin:\$PATH\"
[ -f \"\$HOME/.claude-shared/env.sh\" ] && source \"\$HOME/.claude-shared/env.sh\""
for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
  [[ -f "$rc" ]] || continue
  if grep -qF "claude-profiles.sh" "$rc"; then
    skipped=$((skipped+1))
  else
    act "wire into ${rc#"$HOME"/}"
    (( DRY )) || printf '\n# Claude Code profiles\n%s\n' "$line" >> "$rc"
  fi
done

# ---- 7. source of truth ------------------------------------------------------
if [[ ! -d "$SHARED/.git" ]]; then
  if (( GIT_INIT )); then
    say "initialising a git repository in $SHARED (you asked with --git-init)"
    (( DRY )) || { git -C "$SHARED" init -q; git -C "$SHARED" add -A
      git -C "$SHARED" -c user.email=me@local -c user.name=fde commit -qm "FDE setup $STAMP" || true; }
  else
    note "$SHARED is not a git repository. That is fine — the canonical copy is"
    note "$SRC. Keep that in one private remote and clone it on a new machine."
    note "Pass --git-init if you also want history here."
  fi
fi

printf '\n'
say "done — $added added, $changed updated, $preserved kept as yours, $skipped unchanged"
if (( DRY )); then
  note "dry run: nothing was written."
  exit 0
fi
[[ -d "$BACKUPS" ]] && note "backups of replaced files: $BACKUPS"

cat <<EOF

Open a new shell, then:

  cc-work  cc-msc  cc-alt      personal accounts
  cc-bedrock                   Maxeda on Bedrock (bedrock-dev / eu-west-1,
                               from ~/.claude-profiles/bedrock/settings.json)
  cc-which                     profiles and which one is active
  fde doctor                   what is configured, what is broken

Start the interactive orchestrator workflow:

  fde-start                             choose an orchestrator, then chat
  fde-start --orchestrator bedrock      select the profile directly
  fde status <run-id>                   state, plan, roles and approvals

Cross-tool helpers on your PATH:
  ask-gemini      ask-codex --read-only      ask-ms-copilot
  mcp-sync        regenerate CLI MCP config from one source file

GitHub Copilot is not part of this ecosystem. ask-copilot is a stub that says so.
EOF
